version: "3.9"

services:
  mongo:
    image: "bitnami/mongodb:4.4"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=randompassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    volumes:
      - db:/bitnami/mongodb

volumes:
  db:
    driver: local
